name: macOS Build + Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-verify:
    runs-on: macos-14
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps + tests
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install pytest
          pytest -q

      - name: Prepare stub Ollama for packaging
        run: |
          cat > ollama_binary <<'SH'
          #!/usr/bin/env bash
          echo "ollama stub: $@" >&2
          exit 0
          SH
          chmod +x ollama_binary

      - name: Build embedded python bundle
        run: |
          chmod +x create_python_bundle.sh
          ./create_python_bundle.sh

      - name: Build Debug DMG (Swift-only)
        run: |
          chmod +x build_swift_only.sh
          ./build_swift_only.sh

      - name: Verify DMG (artifact checks + embedded spawn + mock redaction)
        run: |
          chmod +x scripts/verify_bundle.sh || true
          if [ -f scripts/verify_bundle.sh ]; then
            bash scripts/verify_bundle.sh MarcutApp-Swift-*.dmg
          else
            echo "scripts/verify_bundle.sh not present in repo; please add it from upload/scripts/"
            exit 1
          fi

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-dmg
          path: MarcutApp-Swift-*.dmg
          retention-days: 7

